### ISSUE TITLE
Location of the data.json

### ISSUE THREAD

**Issue by vogelino** [fabiantheblind/getting-a-grade-for-io-steel-ant#2]
If I'm right, the data.json file has to be located in this repository and not in each of our repositories. I'm not so sure:
- Is it one single data.json containing data of all studenrs that we extend with our data? (If so why isn't it an array of objects? And where is it?)
- Is it a file called like myname.json in the code folder of this repo?
- Am I wrong and the data.json has to be present in every of our repos? (Should we insert informations about all our projects in one file and then and duplicate this file everywhere? It is quite complicated to keep in sync. Which one will be used for the website?)

@fabiantheblind

**Comment by ff6347** [comment]
@vogelino I just need one data.json for all of your projects and repos. I will concat them all. In the last semesters I learned that nobody understood the idea of a pull request. Wen can try to have one repo here everybody adds his data but I doubt that that will work. Long story short. **One data.json per person**. @FH-Potsdam/steel-ant-io This affects all of you

**Comment by ff6347** [comment]
Or maybe we try it :-)

**Comment by ff6347** [comment]
Add it here [https://github.com/FH-Potsdam/steel-ant-io-data.json](https://github.com/FH-Potsdam/steel-ant-io-data.json)

**Comment by vogelino** [comment]
Okay thx. Should we just add it to the root name like `<githubUserName>.json` so it would be easier for you to find and concatenate them?

**Comment by ff6347** [comment]
Go for it

**Comment by ff6347** [comment]
Ähm. No. I created one json for all of you. You just need to find the element with your GitHub username and then you update your data. :)

**Comment by vogelino** [comment]
Okay I think this time I got it!

**Comment by ff6347** [comment]
Awesome! 🤘🏽
